name: Android-APK
on:
  push:
    branches: [main]      # build every commit
  workflow_dispatch:      # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build with official Buildozer Docker image
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1   # marketplace action[9]
        with:
          workdir: .               # root of repo
          command: buildozer -v android debug
          buildozer_version: stable

      # Upload APK artefact
      - uses: actions/upload-artifact@v4
        with:
          name: FaceApp-APK
          path: bin/*.apk
